[package]
name = "RustBookWalkthrough"
version = "0.1.0"
authors = ["Miles Robson <miles_robson@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
